"""
Feature engineering pipeline for the ML trading project.

Loads collected price data, computes technical indicators, and prepares a dataset
ready for model training. This module should be executed after enough historical
data has been collected.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

from src.utils.config import Config, load_config

try:
    import ta  # type: ignore
except ImportError as error:  # pragma: no cover - optional dependency
    raise SystemExit(
        "The 'ta' package is required for feature computation. "
        "Install it via 'pip install ta'."
    ) from error


def compute_features(frame: pd.DataFrame, config: Config) -> pd.DataFrame:
    """
    Compute technical indicators defined in the configuration.

    Parameters
    ----------
    frame:
        DataFrame with raw price data including 'time', 'bid', 'ask', and optionally OHLC data.
    config:
        Project configuration containing feature parameters.

    Returns
    -------
    DataFrame containing engineered features and target labels.
    """
    feature_cfg = config.feature_engineering
    price_series = frame["bid"].astype(float)

    # Exponential moving averages
    frame["ema_fast"] = ta.trend.EMAIndicator(
        close=price_series,
        window=feature_cfg.get("ema_fast_period", 10),
    ).ema_indicator()
    frame["ema_slow"] = ta.trend.EMAIndicator(
        close=price_series,
        window=feature_cfg.get("ema_slow_period", 30),
    ).ema_indicator()

    # Momentum indicators
    frame["rsi"] = ta.momentum.RSIIndicator(
        close=price_series,
        window=feature_cfg.get("rsi_period", 14),
    ).rsi()
    macd = ta.trend.MACD(
        close=price_series,
        window_slow=feature_cfg.get("macd_slow", 26),
        window_fast=feature_cfg.get("macd_fast", 12),
        window_sign=feature_cfg.get("macd_signal", 9),
    )
    frame["macd"] = macd.macd()
    frame["macd_signal"] = macd.macd_signal()
    frame["macd_hist"] = macd.macd_diff()
    frame["momentum"] = ta.momentum.WilliamsRIndicator(
        high=frame.get("high", price_series),
        low=frame.get("low", price_series),
        close=price_series,
        lbp=feature_cfg.get("williams_period", 14),
    ).williams_r()

    # Volatility features
    frame["atr"] = ta.volatility.AverageTrueRange(
        high=frame.get("high", price_series),
        low=frame.get("low", price_series),
        close=price_series,
        window=feature_cfg.get("atr_period", 14),
    ).average_true_range()

    horizon = feature_cfg.get("target_horizon_minutes", 5)
    frame["future_bid"] = price_series.shift(-horizon)
    frame["target"] = (frame["future_bid"] > price_series).astype(int)
    frame = frame.drop(columns=["future_bid"])

    frame = frame.dropna().reset_index(drop=True)
    return frame


def parse_args() -> argparse.Namespace:
    """Parse CLI arguments."""
    parser = argparse.ArgumentParser(description="Compute technical features for model training.")
    parser.add_argument(
        "--config",
        type=Path,
        default=Path("config/default.yaml"),
        help="Path to YAML configuration file.",
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("data/raw/collector.csv"),
        help="Path to input CSV generated by the data collector.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("data/processed/features.parquet"),
        help="Path to output dataset (Parquet format).",
    )
    return parser.parse_args()


def main() -> None:
    """Entry point for feature engineering."""
    args = parse_args()
    config = load_config(args.config)

    frame = pd.read_csv(args.input, parse_dates=["time"])
    frame = compute_features(frame, config)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    frame.to_parquet(args.output, index=False)
    print(f"Saved features with shape {frame.shape} to {args.output}")


if __name__ == "__main__":
    main()

